config/routes.rb
Rails.application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
  get 'ngbreweries', to: 'breweries#nglist'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'ice_account', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :memberships do
    post 'confirm_application', on: :member
  end

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:delete]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @users_confirmed = Membership.where(beer_club_id: @beer_club.id, confirmed: true).pluck(:user_id).map{ |u| User.find(u) }
    @users_pending = Membership.where(beer_club_id: @beer_club.id, confirmed: false).pluck(:user_id).map{ |u| User.find(u) }
    unless @users_confirmed.include?(current_user)
      @membership = Membership.new
      @membership.beer_club = @beer_club
      #@membership.user = current_user
    else
      @membership = Membership.where(beer_club_id: @beer_club.id, user_id: current_user.id).first
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    respond_to do |format|
      if @beer_club.save
        Membership.create(user_id: current_user.id, beer_club_id: @beer_club.id, confirmed: true)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn-sm btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<br />
<%= link_to 'Delete', @beer_club, method: :delete, data: {confirm:'Are you sure?'}, class:"btn-sm btn-danger" if current_user.admin %>
<%= link_to 'Back', @beer_club, class:"btn-sm btn-primary" %>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Beer Clubs</h2>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer club', new_beer_club_path, class:"btn-sm btn-primary") if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @beer_club.name %> <%= @beer_club.city %>
</h2>

<p>
  Founded <%= @beer_club.founded %>
</p>

<h4>Members</h4>  
  <table class="table table-striped table-condensed">
    <% @users_confirmed.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
      </tr>
    <% end %>
  </table>
<br />


<% if current_user %>
  <% if @users_confirmed.include?(current_user) and @users_pending.size > 0 %>
    <h4>Pending applications</h4>
    <table class="table table-striped table-condensed">
    <% @users_pending.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= link_to 'Confirm', confirm_application_membership_path(beer_club_id: @beer_club.id, user_id: user.id), method: :post, class:"btn-sm btn-primary" %>
      </tr>
    <% end %>
  </table>
<br /><br />
  <% end %>
  <% unless @users_pending.include?(current_user) %>
    <% if @users_confirmed.include?(current_user) %>
      <%= form_for(@membership, method: "delete") do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.submit value: "End the membership", class:"btn-sm btn-primary" %>
      <% end %>
    <% end %>
    <% unless @users_confirmed.include?(current_user) %>
      <%= form_for(@membership) do |f| %>
        <%= f.hidden_field :beer_club_id %>
          <%= f.submit value:"Join the club", class:"btn-sm btn-primary" %>
      <% end %>
    <% end %>
  <% end %>
<br /><br />
  <%= link_to 'Edit', edit_beer_club_path(@beer_club), class:"btn-sm btn-primary" %>
<% end %>
<%= link_to 'Back', beer_clubs_path, class:"btn-sm btn-primary" %>