config/routes.rb
Rails.application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
  get 'ngbreweries', to: 'breweries#nglist'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'ice_account', on: :member
  end
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :memberships do
    post 'confirm_application', on: :member
  end

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :name, presence: true
  validate :acceptable_year

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil, false] }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  def print_report
    puts self.name
    puts "established at year #{self.year}"
    puts "number of beers #{self.beers.count}"
  end

  def restart
    self.year = 2015
    puts "changed year to #{year}"
  end

  def acceptable_year
    unless year.present? && year >= 1042 && year <= Time.now.year
      errors.add(:year, "has to be present and between 1042 and this year")
    end
  end

  def self.top_breweries(n)
    Brewery.all.sort_by{ |b| -(b.average_rating) }.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list, :nglist]
  before_action :ensure_that_admin, only: [:delete]
  before_action :skip_if_cached, only: [:index]
  before_action :expire_fragments, only: [:create, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    case @order
      when 'name' 
        @active_breweries = Brewery.active.order('lower(name)')
        @retired_breweries = Brewery.retired.order('lower(name)')
        session[:brewery_order] = "name"
      when 'year'
        if session[:brewery_order] == "year_down"
          @active_breweries = Brewery.active.order(:year).reverse
          @retired_breweries = Brewery.retired.order(:year).reverse
          session[:brewery_order] = "year_up"
        else
          @active_breweries = Brewery.active.order(:year)
          @retired_breweries = Brewery.retired.order(:year)
          session[:brewery_order] = "year_down"
        end
    end
    @breweries = Brewery.all    
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)
    new_status = brewery.active? ? "active" : "retired"
    redirect_to :back, notice:"Brewry activity status changed to #{new_status}"
  end

  def brewerylist
  end

  def ngbreweries
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    def skip_if_cached
      @order = params[:order] || 'name'
        if fragment_exist?("breweries-#{@order}")
          return render :index 
        end
    end

    def expire_fragments
        ["breweries-name", "breweries-year"].each{ |f| expire_fragment(f) }
        session[:brewery_order] = ""
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

end

app/helpers/breweries_helper.rb
module BreweriesHelper

end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn-sm btn-primary" %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order:"name") %></th>
      <th><%= link_to 'Year', breweries_path(order:"year") %></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= edit_and_destroy_buttons(brewery) %></td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<br />
<% if current_user.admin %>
  <%= link_to 'Delete', @brewery, method: :delete, notice:"Are you sure", class:"btn-sm btn-danger"%>
<% end %>
<%= link_to 'Back', @brewery, class:"btn-sm btn-primary" %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Breweries</h2>

<%= @session %>

<% cache "breweries-#{@order}", skip_digest: true do %>

<h3>Active</h3>

<p> Number of active breweries: <%= @active_breweries.count %></p>

<%= render 'list', breweries: @active_breweries %>

<h3>Retired</h3>

<p>Number of retired breweries: <%= @retired_breweries.count %></p>

<%= render 'list', breweries: @retired_breweries %>

<% end %>

<br />

<%= link_to('New Brewery', new_brewery_path, class:"btn-sm btn-primary") if current_user %>

<br>

<%#= link_to 'List of beers', beers_path %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-condensed table-striped">
  <tr>
    <th><a href="#" id="brewname">Name</th>
    <th><a href="#" id="year">Year</th>
    <th><a href="#" id="number">Number of Beers</th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order) {
      $scope.order = order;
      console.log(order);
    }
  });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  <table class="table table-striped table-condensed">
    <thead>
      <th><a ng-click="sort_by('name')">Name</a></th>
      <th><a ng-click="sort_by('year')">Year</a></th>
      <th><a ng-click="sort_by('beers.count')">Number of Beers</a></th>
    </thead>
    <tr ng-repeat="brewery in breweries | orderBy:order">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
      <td>{{brewery.beers.count}}</td>
    </tr>
  </table>

</div>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @brewery do %>

<h2>
  <%= @brewery.name %>
  <% unless @brewery.active %>
    <span class="badge">retired</span>
  <% end %>
</h2>

<p>
  <i>Established in</strong>
  <%= @brewery.year %></i>
</p>

<br />
<p>
  Number of <strong>Beers</strong>
  <%= @brewery.beers.count %>
</p>

<table class="table table-striped table-condensed">
  <% @brewery.beers.each do |beer| %>
    <tr>
      <td><%= link_to beer.name, beer %></td>
    </tr>
  <% end %>
</table>
<br />

<p>
  Has <%= pluralize(@brewery.ratings.count, 'rating', 'ratings')%><% if @brewery.ratings.count > 0 %>, average <%= round(@brewery.average_rating) %>
  <% end %>
</p>
<br />

<% end %>

<% if current_user %>
  <%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class:"btn-sm btn-primary" %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class:"btn-sm btn-primary" %> 
<% end %>